spring:
  datasource:
    url: jdbc:mysql://localhost:3306/cubtest
    username: root
    password: 11coco
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    database-platform: org.hibernate.dialect.MySQL5Dialect
    hibernate:
      ddl-auto: update
    show-sql: true
